### ISSUE TITLE
How to make it work with @reach/tabs

### ISSUE THREAD

**Issue by gaurav-nelson** [alexkrolick/mdx-observable#2]
PS: https://github.com/reach/reach-ui/issues/238

Thank you for creating this and your associated blog post about interactive documentation. I want to try to use this component to control multiple tabs on an MDX page. I am still a beginner in working with React + Gatsby + MDX and I've been trying various approaches to solve this issue. 

### Issue

If I have a page with mutiple tabs with same labels:
```
Heading 1

First tab block
Tab 1 | Tab 2
Content Tab 1

Second tab block
Tab 1 | Tab 2
Content Tab 1 for second block

Third tab block
Tab 1 | Tab 2
Content Tab 1 for third block
```

### Sample code
I am trying to create a Tab component for a Gatsby site. 
1. I created a 'CoLocatedTabs' component (with controlled behavior)
Code: https://github.com/gaurav-nelson/gatsby-gitbook-starter/blob/master/src/components/tabsTest.js
2. Imported it into MDX (twice)
Code: https://raw.githubusercontent.com/gaurav-nelson/gatsby-gitbook-starter/master/content/introduction.mdx
3. In rendered version I get two separate tab components which don't talk to each other. 

What I want is that when I switch to "Tab 2" all tabs on page should switch to "Tab 2". 

I was wondering if this is achievable by using mdx-observable? And if you can share examples, it would be awesome.

**Comment by alexkrolick** [comment]
I guess it is, if you can keep the active tab index in state and reference that as a prop for each tab usage

**Comment by gaurav-nelson** [comment]
Thanks for your response, I tried few different combinations (trial and error basically) but couldn't make it work. I am new to react, so if you can provide and example, that'd be super helpful. 🙇

**Comment by alexkrolick** [comment]
https://codesandbox.io/embed/gatsby-mdx-tabs-linked-state-demo-rkb8v

**Comment by gaurav-nelson** [comment]
@alexkrolick Thank you so much for this. Now I know what went wrong. I was using the main `State` inside my component.
